# generated by generate-favicon-globe.mjs
from PIL import Image, ImageFilter
import numpy as np
import os

SRC = "C:/owenminercs/owenminercs/dev/tmp-logo/favicon-build/source-52s.png"
OUT = "C:/owenminercs/owenminercs/images/logo"
WORK = "C:/owenminercs/owenminercs/dev/tmp-logo/favicon-build"
FILL_RATIO = 0.93

# Foliage bright green sampled from source frame highlights
GREEN_HI = np.array([80, 254, 106])   # #50fe6a
GREEN_MID = np.array([45, 138, 62])   # #2d8a3e
GREEN_LO = np.array([18, 72, 38])     # #124826

img = Image.open(SRC).convert('RGBA')
arr = np.array(img, dtype=np.float32)
h, w = arr.shape[:2]
r, g, b = arr[:, :, 0], arr[:, :, 1], arr[:, :, 2]

# Auto-detect red marble globe center/radius (fallback to hand-tuned 0:52 values)
red_globe = (r > 55) & (r > g + 18) & (g < 90)
ys, xs = np.where(red_globe)
if xs.size > 500:
    CX = int(np.median(xs))
    CY = int(np.median(ys))
    dists = np.sqrt((xs - CX) ** 2 + (ys - CY) ** 2)
    R = int(np.percentile(dists, 97))
else:
    CX, CY, R = 904, 522, 200

Y, X = np.ogrid[:h, :w]
dist = np.sqrt((X - CX) ** 2 + (Y - CY) ** 2)

# Full circular globe — do NOT punch foliage holes (that breaks the silhouette)
inside = dist <= R
edge_aa = 1.8
alpha_mask = np.clip((R - dist) / edge_aa + 0.5, 0, 1)

# Spherical normal shading (light upper-left) for readable 3D globe
nx = np.clip((X - CX) / max(R, 1), -1, 1)
ny = np.clip((Y - CY) / max(R, 1), -1, 1)
nz_sq = np.clip(1.0 - nx * nx - ny * ny, 0, 1)
nz = np.sqrt(nz_sq)
light = np.array([-0.55, -0.45, 0.70], dtype=np.float32)
light /= np.linalg.norm(light)
sphere_shade = np.clip(nx * light[0] + ny * light[1] + nz * light[2], 0, 1)
# Rim darkening for depth
rim = np.clip(nz, 0, 1) ** 0.35
sphere_shade = sphere_shade * (0.55 + 0.45 * rim)

# Source marble texture luminance from red globe pixels
globe_tex = inside & (r > 40) & (r > g + 10)
lum = 0.299 * r + 0.587 * g + 0.114 * b
tex_lum = np.full((h, w), 0.5, dtype=np.float32)
if globe_tex.any():
    lo, hi = np.percentile(lum[globe_tex], [6, 94])
    span = max(hi - lo, 1.0)
    tex_lum = np.clip((lum - lo) / span, 0, 1)

# Blend sphere lighting with source texture (texture adds marbling)
t = np.clip(0.52 * sphere_shade + 0.48 * tex_lum, 0, 1)
# Slight contrast boost for small sizes
t = np.clip((t - 0.5) * 1.12 + 0.5, 0, 1)

# Two-stop green gradient: shadow -> highlight via mid
color = np.zeros((h, w, 3), dtype=np.float32)
for i in range(3):
    mid_blend = GREEN_MID[i] + (GREEN_HI[i] - GREEN_MID[i]) * (t ** 1.15)
    shadow_blend = GREEN_LO[i] + (GREEN_MID[i] - GREEN_LO[i]) * (t ** 0.85)
    color[:, :, i] = np.where(t > 0.42, mid_blend, shadow_blend)

out = np.zeros((h, w, 4), dtype=np.uint8)
out[inside, :3] = np.clip(color[inside], 0, 255).astype(np.uint8)
out[:, :, 3] = np.clip(alpha_mask * 255, 0, 255).astype(np.uint8)
out[~inside, 3] = 0

# Tight square crop on globe circle (minimal padding)
side = int(R * 2)
left = max(CX - R, 0)
top = max(CY - R, 0)
right = min(left + side, w)
bottom = min(top + side, h)
if right - left < side:
    left = max(right - side, 0)
if bottom - top < side:
    top = max(bottom - side, 0)

cropped = Image.fromarray(out[top:bottom, left:right], 'RGBA')
cropped.save(os.path.join(WORK, 'globe-green-preview.png'))

def render(size, *, fill=FILL_RATIO, sharpen_small=False):
    target = max(int(round(size * fill)), 1)
    resized = cropped.resize((target, target), Image.Resampling.LANCZOS)
    if sharpen_small and size <= 32:
        resized = resized.filter(ImageFilter.UnsharpMask(radius=0.6, percent=130, threshold=2))
    canvas = Image.new('RGBA', (size, size), (0, 0, 0, 0))
    offset = (size - target) // 2
    canvas.paste(resized, (offset, offset), resized)
    return canvas

render(16, sharpen_small=True).save(os.path.join(OUT, 'favicon-16.png'))
render(32, sharpen_small=True).save(os.path.join(OUT, 'favicon-32.png'))
render(180).save(os.path.join(OUT, 'apple-touch-icon.png'))

ico_sizes = [16, 32, 48]
ico_images = [
    render(s, sharpen_small=(s <= 32)).convert('RGBA') for s in ico_sizes
]
ico_images[0].save(
    os.path.join(OUT, 'favicon.ico'),
    format='ICO',
    sizes=[(s, s) for s in ico_sizes],
    append_images=ico_images[1:],
)

# Verify transparency — no dark matte pixels outside globe
for name in ['favicon-16.png', 'favicon-32.png', 'apple-touch-icon.png']:
    p = os.path.join(OUT, name)
    a = np.array(Image.open(p).convert('RGBA'))[:, :, 3]
    assert a[a == 0].size > 0, f'{name}: expected transparent pixels'
    rgb = np.array(Image.open(p).convert('RGBA'))[:, :, :3]
    opaque = a > 128
    if opaque.any():
        dark = (rgb[opaque].max(axis=1) < 20).sum()
        assert dark == 0, f'{name}: found {dark} near-black opaque pixels'

print('Done.')
print(f'Frame: 0:52s from {os.path.basename("j:/Bubble logo folder/owenminercslogo.mp4")}')
print(f'Globe: center ({CX},{CY}) radius {R}px, crop {side}x{side}')
print(f'Fill ratio: {FILL_RATIO:.0%} of canvas')
print(f'Green: hi #50fe6a mid #2d8a3e lo #124826')
print(f'Background: transparent (all outputs)')
print(f'Output: {OUT}')
